package constants

// log_templates.go 集中定义全部日志格式字符串（≥25 条）。
const (
	LOG_USER_REGISTER_START      = "User register start"
	LOG_USER_REGISTER_SUCCESS    = "User register success"
	LOG_USER_LOGIN_SUCCESS       = "User login success"
	LOG_USER_LOGIN_FAILED        = "User login failed"
	LOG_USER_PROFILE_UPDATED     = "User profile updated"
	LOG_CATEGORY_CREATED         = "Category created"
	LOG_CATEGORY_UPDATED         = "Category updated"
	LOG_CATEGORY_DELETED         = "Category deleted"
	LOG_TAG_CREATED              = "Tag created"
	LOG_TAG_UPDATED              = "Tag updated"
	LOG_TAG_DELETED              = "Tag deleted"
	LOG_ARTICLE_CREATED          = "Article created"
	LOG_ARTICLE_UPDATED          = "Article updated"
	LOG_ARTICLE_DELETED          = "Article deleted"
	LOG_ARTICLE_PUBLISHED        = "Article published"
	LOG_ARTICLE_VIEWED           = "Article viewed"
	LOG_ARTICLE_SEARCHED         = "Article searched"
	LOG_ARTICLE_SLUG_CONFLICT    = "Article slug conflict"
	LOG_COMMENT_CREATED          = "Comment created"
	LOG_COMMENT_APPROVED         = "Comment approved"
	LOG_COMMENT_DELETED          = "Comment deleted"
	LOG_COMMENT_REJECTED         = "Comment rejected"
	LOG_STATS_GENERATED          = "Site stats generated"
	LOG_ARCHIVE_GENERATED        = "Archive generated"
	LOG_REDIS_CONNECTED          = "Redis connected"
	LOG_REDIS_ERROR              = "Redis operation failed"
	LOG_DB_INITIALIZED           = "Database initialized"
	LOG_SERVER_STARTED           = "Server started"
	LOG_SERVER_SHUTDOWN          = "Server shutdown"
	LOG_RATE_LIMITED             = "Request rate limited"
	LOG_REQUEST_START            = "Request start"
	LOG_REQUEST_FINISH           = "Request finish"
	LOG_PANIC_RECOVERED          = "Panic recovered"
)
